config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :articulos

end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
    has_many :comentarios
    
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
    belongs_to :articulo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :set_articulo, only: [:show, :edit, :update, :destroy]

  # GET /articulos
  # GET /articulos.json
  def index
    @articulos = Articulo.all
  end

  # GET /articulos/1
  # GET /articulos/1.json
  def show
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: 'Articulo creado exitosamente.' }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1
  # PATCH/PUT /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: 'Articulo actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo.destroy
    respond_to do |format|
      format.html { redirect_to articulos_url, notice: 'Articulo eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articulo_params
      params.require(:articulo).permit(:titulo, :cuerpo, :fecha)
    end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @articulo = Articulo.find_by_id(params[:articulo_id])
    @comentario = Comentario.new(articulo_id: @articulo.id)
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario creado exitosamente.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:Autor, :cuerpo, :fecha, :articulo_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/articulos/_form.html.erb
<%= form_for(@articulo) do |f| %>
  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>

      <ul>
      <% @articulo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field input-group">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, :class =>"form-control" %>
  </div>
  <div class="field input-group">
    <%= f.label :cuerpo %><br>
    <%= f.text_area :cuerpo, :class =>"form-control" %>
  </div>
  <div class="field input-group">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar", :class =>"btn btn-success" %>
  </div>
<% end %>

app/views/articulos/edit.html.erb
<h1 id="nart">Editar articulo</h1>

<%= render 'form' %>

  <div class="actions">
    <%= link_to 'Ver', @articulo, :class =>"btn btn-info" %>
    <%= link_to 'Volver', articulos_path, :class =>"btn btn-warning" %>
  </div>

app/views/articulos/index.html.erb
<% unless notice.blank? %>
<div class="alert alert-success" role="alert">
  <p id="notice"><%= notice %></p>
</div>
<% end %>

<h1 id="princ">Listado de Articulos</h1>
<!-- 
<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Cuerpo</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articulos.each do |articulo| %>
      <tr>
        <td><%= articulo.titulo %></td>
        <td><%= articulo.cuerpo %></td>
        <td><%= articulo.fecha %></td>
        <td><%= link_to 'Ver', articulo %></td>
        <td><%= link_to 'Editar', edit_articulo_path(articulo) %></td>
        <td><%= link_to 'Eliminar', articulo, method: :delete, data: { confirm: '¿Esta usted seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->
<br>


<table>
  <thead>
    <tr>
      <th>Titulo </th>
      <th>Cuerpo </th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articulos.each do |articulo| %>
      <tr>
        <td><%= articulo.titulo %></td>
        <td><%= articulo.cuerpo %></td>
        <td><%= articulo.fecha %></td>
        <td>
            <div class="actions">
              <%= link_to 'Ver', articulo, :class =>"btn btn-default btn-xs" %>
            </div>
        </td>
        <td>
            <div class="actions">
              <%= link_to 'Editar', edit_articulo_path(articulo), :class =>"btn btn-default btn-xs" %>
            </div>  
        </td>
        <td>
            <div class="actions">
              <%= link_to 'Eliminar', articulo, method: :delete, data: { confirm: '¿Esta usted seguro?' }, :class =>"btn btn-default btn-xs" %>
            </div> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


  <div class="actions">
    <%= link_to 'Nuevo Articulo', new_articulo_path, :class =>"btn btn-success" %>
  </div>
<!-- 
<ul class="media-list">
  <li class="media">A
    <ul>   
      <li class="media"><span class="glyphicon glyphicon-check" aria-hidden="true"></span> Trabajo especial de Grado. Propuesta de diseño de una red que permita el acceso a Wifi garatis en los lugares públicos de las parroquias La Candelaria, San Agustin, San Bernanrdino y 23 de Enero del Municipio Libertador</li>
      <li class="media">Trabajo especial de Grado. Propuesta de diseño de una red que permita el acceso a Wifi garatis en los lugares públicos de las parroquias La Candelaria, San Agustin, San Bernanrdino y 23 de Enero del Municipio Libertador</li>
      <li class="media">Trabajo especial de Grado. Propuesta de diseño de una red que permita el acceso a Wifi garatis en los lugares públicos de las parroquias La Candelaria, San Agustin, San Bernanrdino y 23 de Enero del Municipio Libertador</li>
      <li class="media">Trabajo especial de Grado. Propuesta de diseño de una red que permita el acceso a Wifi garatis en los lugares públicos de las parroquias La Candelaria, San Agustin, San Bernanrdino y 23 de Enero del Municipio Libertador</li>
    </ul>
  </li>
  <li class="media">B</li>
  <li class="media">C</li>
  <li class="media">D</li>
</ul>

<div class="container">
     <div class="row">
        <div class= "col-lg-4 col-md-6 col-sm-6 col-xs-12">
          Wifi en los lugares públicos del Municipio Libertador. 
        </div>
         <div class= "col-lg-4 col-md-6 col-sm-6 col-xs-12">
          Presentada por Paola Palencia en Octubre de 2014. 
        </div>
        <div class= "col-lg-4 col-md-6 col-sm-6 col-xs-12">
          Trabajo especial de Grado. Propuesta de diseño de una red que permita el acceso a Wifi garatis en los lugares públicos de las parroquias La Candelaria, San Agustin, San Bernanrdino y 23 de Enero del Municipio Libertador
        </div>
     </div>
</div>
-->

app/views/articulos/new.html.erb
<h1 id="nart">Nuevo Articulo</h1>

<%= render 'form' %>

  <div class="actions">
    <%= link_to 'Volver', articulos_path, :class =>"btn btn-warning" %>
  </div>

app/views/articulos/show.html.erb
<% unless notice.blank? %>
<div class="alert alert-success" role="alert">
  <p id="notice"><%= notice %></p>
</div>
<% end %>
<p>
  <strong>Titulo:</strong><em>
  <%= @articulo.titulo %></em>
</p>

<p>
  <strong>Cuerpo:</strong><em>
  <%= @articulo.cuerpo %></em>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @articulo.fecha %>
</p>

  <div class="actions">
    <%= link_to 'Editar', edit_articulo_path(@articulo), :class =>"btn btn-primary" %>
    <%= link_to 'Volver', articulos_path, :class =>"btn btn-warning" %>
  </div>
<!-- 
<h3 id="tit">Comentarios</h3>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Cuerpo</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articulo.comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.Autor %></td>
        <td><%= comentario.cuerpo %></td>
        <td><%= comentario.fecha %></td>
        <td><%= link_to 'Ver', comentario %></td>
        <td><%= link_to 'Editar', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Eliminar', comentario, method: :delete, data: { confirm: '¿Desea eliminar el comentario?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> 
-->

<h3 id="tit">Comentarios</h3>
        <div class="actions">
          <%= link_to 'Nuevo Comentario', new_comentario_path(articulo_id: @articulo.id), :class =>"btn btn-success" %>
        </div>
  <tbody>
    <% @articulo.comentarios.each do |comentario| %>
      <dl>
        <dt><strong><%= comentario.Autor %></strong></dt>
          <dd><%= comentario.cuerpo %></dd>
          <dd>fecha <strong><small><%= comentario.fecha %></small></strong></dd>
            <div class="actions">
              <%= link_to 'Ver', comentario, :class =>"btn btn-info" %>
              <%= link_to 'Editar', edit_comentario_path(comentario), :class =>"btn btn-primary" %>
              <%= link_to 'Eliminar', comentario, method: :delete, data: { confirm: '¿Desea eliminar el comentario?' }, :class =>"btn btn-default" %>
            </div>
          </dl>
    <% end %>
  </tbody>

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <%= f.hidden_field :articulo_id %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Autor %><br>
    <%= f.text_field :Autor %>
  </div>
  <div class="field">
    <%= f.label :cuerpo %><br>
    <%= f.text_area :cuerpo %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit "Crear", :class =>"btn btn-success" %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editar Comentario</h1>

<%= render 'form' %>

  <div class="actions">
    <%= link_to 'Ver', @comentario, :class =>"btn btn-info" %>
    <%= link_to 'Volver', @comentario.articulo, :class =>"btn btn-warning" %>
  </div>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Cuerpo</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.Autor %></td>
        <td><%= comentario.cuerpo %></td>
        <td><%= comentario.fecha %></td>
        <td><%= link_to 'Ver', comentario %></td>
        <td><%= link_to 'Editar', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Eliminar', comentario, method: :delete, data: { confirm: '¿Esta usted seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1 id="nart">Nuevo Comentario</h1>

<%= render 'form' %>

<div class="actions">
    <%= link_to 'Volver', @comentario.articulo, :class =>"btn btn-warning" %>
</div>

app/views/comentarios/show.html.erb
<% unless notice.blank? %>
<div class="alert alert-success" role="alert">
  <p id="notice"><%= notice %></p>
</div>
<% end %>
<p>
  <strong>Autor:</strong><em>
  <%= @comentario.Autor %></em>
</p>

<p>
  <strong>Cuerpo:</strong><em>
  <%= @comentario.cuerpo %></em>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @comentario.fecha %>
</p>

  <div class="actions">
    <%= link_to 'Editar', edit_comentario_path(@comentario), :class =>"btn btn-primary" %>
    <%= link_to 'Volver', @comentario.articulo, :class =>"btn btn-warning" %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>

<%= yield %>

<center>Hecho por Paola Palencia</center>
<center>contacto paopalen@gmail.com</center>

</body>
</html>